spring.application.name=branch-api
server.port=8080

# MSSQL
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=TESTDB;encrypt=true;trustServerCertificate=true}
spring.datasource.username=branchapi
spring.datasource.password=BranchApi#2026
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Connection pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=10000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# API errors
server.error.include-message=always

# Logging
logging.file.name=logs/application.log
logging.level.root=INFO
logging.level.com.logan.branchapi=DEBUG

# Open-Meteo configuration
weather.api.base-url=https://api.open-meteo.com
weather.api.connect-timeout=3s
weather.api.read-timeout=5s